apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web-app
  annotations:
    backstage.io/kubernetes-id: web-app
spec:
  lifecycle: experimental
  owner: demo
  type: service

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: demo
spec:
  type: team
  children: []
  
